name: Title Generator Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH and Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: josegarrera
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker stop title-generator || true
            docker rm title-generator || true
            docker pull josegarrera/title-generator:${{ github.sha }}
            docker run -d --name title-generator -p 3002:3002 josegarrera/title-generator:${{ github.sha }}
